title: Python Git Actions
author:
  name: Om
  email: omprakashmishra3978@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  This repo explains how GH Actions could be used to run python scripts on a schedule basis.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: isTrueEqlFalse
    github:  mishraomp

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
