name: Execute Python Script in Dev environment
on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
 Execute_Python_Script_in_Dev_environment:
   runs-on: ubuntu-latest
   environment: dev
   steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
      with:
        ref: dev
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 #install the python needed
    - name: add pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv
    - name: install dependencies
      run: pipenv install --deploy
    #- run: pipenv lock -r > requirements.txt
    #- name: install dependencies
    #  run: pip install -r requirements.txt
    - name: execute python script # run the main.py to get the latest data
      env:
        API_KEY: ${{ secrets.API_KEY }}
        LOG_LEVEL: DEBUG
      run: |
        pipenv run python app/main.py


