name: Execute Python Script in Dev environment
on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
 Execute_Python_Script_in_Dev_environment:
   runs-on: ubuntu-latest
   environment: dev
   steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to GitHub runner.
      with:
        ref: deploy/dev # Specify the branch to checkout.
    - name: setup python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 #install the python version needed
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv
    - name: install python script dependencies
      run: pipenv install --deploy
    - name: execute the python script # run the main.py to get the latest data
      env:
        API_KEY: ${{ secrets.API_KEY }}
        LOG_LEVEL: DEBUG
      run: |
        pipenv run python app/main.py


